### ISSUE TITLE
Missing bracket on line 13 of Dockerfile

### ISSUE THREAD

**Issue by cromulus** [praekeltfoundation/rp-indexer-docker#1]
https://github.com/praekeltfoundation/rp-indexer-docker/blob/9284218461ef2d66f1f328d89db1621ac7c427ba/Dockerfile#L13

Also, does this need to expose a port? I don't think so...

**Comment by rudigiesler** [comment]
Fixed by https://github.com/praekeltfoundation/rp-indexer-docker/commit/de51e36c945fad4b0d6427190881fecbf2109193
